syncthing:
  service:
    web:
      type: ClusterIP
      port: 8384
    tcp:
      type: NodePort # Change to LoadBalancer if you want to expose the service
      port: 22000
    udp:
      type: NodePort # Change to LoadBalancer if you want to expose the service
      port: 22000
    discovery:
      type: NodePort # Change to LoadBalancer if you want to expose the service
      port: 21027

  nodeSelector:
    location: "local"
  
  persistence:
    enabled: true
    storageClass: "longhorn-local"
    accessMode: ReadWriteOnce
    size: 2Gi
    mountPath: /var/syncthing
    extraVolumes:
      - name: files
        mountPath: /mnt/files
        existingClaim: "syncthing-files"