apiVersion: v2
name: jellyfin
description: Jellyfin Helm Chart
type: application
version: 0.1.1

dependencies:
  - name: jellyfin
    repository: https://diademiemi.github.io/charts
    version: 0.1.1