apiVersion: v2
name: Syncthing
description: Syncthing Helm Chart
type: application
version: 0.1.3

dependencies:
  - name: syncthing
    repository: https://diademiemi.github.io/charts
    version: 0.1.3