apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-files-pv
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: syncthing
    name: syncthing-files
  storageClassName: "local-path"
  capacity:
    storage: 2048Gi
  local:
    path: "/mnt/files"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "k3s.io/hostname"
              operator: In
              values:
                - omori