apiVersion: v2
name: Joplin Server
description: Joplin Server Helm Chart
type: application
version: 0.2.0

dependencies:
  - name: joplin-server
    repository: https://diademiemi.github.io/charts
    version: 0.2.0