vaultwarden:
  image:
    repository: vaultwarden/server
    tag: latest
    pullPolicy: IfNotPresent

  env:
    SIGNUPS_ALLOWED: true
    INVITATIONS_ALLOWED: true
    DOMAIN: https://vault.blahaj.sh
    SMTP_HOST: blahaj.sh
    SMTP_FROM: no-reply@blahaj.sh
    WEB_VAULT_ENABLED: true

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      kubernetes.io/tls-acme: "false"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    path: /
    hosts:
      - vault.blahaj.sh
    tls:
      - secretName: vaultwarden-blahaj-cert
        hosts:
          - vault.blahaj.sh
    pathType: Prefix

  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    size: 3200Mi
    storageClass: longhorn-replicated
    #existingClaim: "bitwarden-pvc"
